### PR TITLE
Update specification based on external review 

### LINKED ISSUE #9: Create feature branch for external review
Starting from the master a new branch `issue9_externalReview` is created to initiate the external review process through the Github PR review feature. 
The new version `1.2` of the specification from this feature branch will include the review outputs.
This will complete Task 1 of the project.

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #9

### CODE REVIEW

**Review by WatchMeCalculate — APPROVED** [review]

**Comment by WatchMeCalculate** [comment]
@AntoineGautier Looks like I don't have write access to this repo. Would you mind granting that?

**Comment by AntoineGautier** [comment]
@WatchMeCalculate Done.

**Comment by AntoineGautier** [comment]
Following "Linkage Requirement Examples" meeting on 11/16, the following items need to be further specified.

- [ ] For a given system type (e.g., AHU but it might be good to consider also a chilled water plant to provide another example of the complexity that the templates must cover) 
  - [ ] Enumerate the different configurations (both equipment and controls) that need to be represented
    - It might be good to have someone from Taylor Eng. to validate our selection. 
  - [ ] Provide the mapping with the classes from the Modelica Buildings Library
    - This is expected to be incomplete as some components (e.g., run-around coil heat recovery or steam coil) do not have a corresponding model implemented yet. However, we should flag what is missing in MBL and open issues for feature enhancement on MBL repo. The remaining (currently available in MBL) should be considered as a target for Phase I.
  - [ ] Generate two Modelica models representing two different system configurations
    - Those may be used ultimately to validate Linkage output files.
- [ ] Update the specification for the placement grid, see https://lbl-srg.github.io/linkage.js/requirements.html#grid
  - It might be beneficial to rely directly on a Modelica diagram layout rather than on a tailored grid layout as described currently. The template developer would place the different components on the diagram layout of a Modelica model (using any Modelica graphical editor) without connecting them together. The templating engine would parse that Modelica file (formatted in JSON) and use the component names, the description strings (and the annotations if needed) and the placement coordinates (considered as relative rather than absolute) together with the configuration file (that would reference the above information) to generate the required Modelica model (formatted in JSON).
- [ ] Further specify the mechanism supporting a variable number of instances, see https://lbl-srg.github.io/linkage.js/requirements.html#format
  - Either use an array syntax or a given offset of the component placement coordinates. Or support the two. 
    > An AHU with a 20 fan array should be supported.
- [ ] Further specify the mechanism to propagate and expose some component parameters (e.g., records with fan curves)
- [ ] Specify how to handle 1) the required sensors (needed by the control sequence), 2) optional sensors for trending or fault detection, and 3) optional sensors for simulation diagnostics
  - The logic "if not connected to a block connector of a CDL component, do not instantiate" comes short for the second category. Except if we introduce a dedicated trending block in the CDL package.
  - Note that the second category should also be part of the I/O point list.
  - Also note that some sensors (e.g., at the terminal unit level) may be required by a control option specified in another template (e.g., at the plant level).

**Comment by AntoineGautier** [comment]
I merged the modifications related to the use of Modelica for templating.
The PDF is available at https://github.com/lbl-srg/linkage.js/blob/issue9_externalReview/specification/build/latex/Linkage.pdf
The HTML is available online on my private repo for now, at https://antoinegautier.github.io/linkage.js/ or for download at https://github.com/lbl-srg/linkage.js/tree/issue9_externalReview/specification/build/html

**Comment by WatchMeCalculate** [comment]
@AntoineGautier  I've read through the updated pdf and it all looks good, I had a responses to your `todo` questions and a question of my own:

For 3.3.1:
My suggestion would be for values that are required and not filled in, for the first revision at least i'm leaning towards we provide defaults, this would lend towards being easier for a user to use. If conditionals are able to be used we could conditionally set a default based on a catalyst setting before: i.e `if hvac.system.None then value =20.5` or something like that. 

Something else i'm thinking about right now, an input value shouldn't be updated until a system is completely chosen. As in all options have been chosen to create a valid system


For 3.3.1.2:

I though we were going to override the resulting class and when it is converted back to modelica it would be baked into the code? The todo here seems to suggest we would be storing it separately from that 


In 3.3.4
For the first bullet of step 6, the widget will be working exclusively with a json representation of the system provided, does the json representation support extending a template class?

**Comment by AntoineGautier** [comment]
@WatchMeCalculate Thanks for looking into that!

> My suggestion would be for values that are required and not filled in, for the first revision at least i'm leaning towards we provide defaults, this would lend towards being easier for a user to use.

What came out from the user interviews is that for the control configuration workflow, providing no default for parameters that scale (typically sizing parameters) is fine as the control sequence specification typically does not bother about equipment characteristics but only about system layout and control options.

> If conditionals are able to be used we could conditionally set a default based on a catalyst setting before: i.e `if hvac.system.None then value =20.5`.

Parameters cannot be conditionally declared, see "A component declared with a condition-attribute can only be modified and/or used in connections" in https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#conditional-component-declaration.

> Something else i'm thinking about right now, an input value shouldn't be updated until a system is completely chosen. As in all options have been chosen to create a valid system.

If I understand correctly, in the configuration workflow the user has only access to "structural parameters" that define the system layout and control options. The configuration widget spits out this valid configured system model that can be instantiated in third-party tools and parameterized with equipment sizing characteristics, etc.

I agree with this.

> I though we were going to override the resulting class and when it is converted back to modelica it would be baked into the code? The todo here seems to suggest we would be storing it separately from that

I need to discuss that with you, I don't see exactly what you are referring to.

> For the first bullet of step 6, the widget will be working exclusively with a json representation of the system provided

Yes

> does the json representation support extending a template class?

The json representation can contain any valid extend clauses. But the extend clause needed here must be generated by the widget, with the class modification corresponding to the user inputs. For instance (using Modelica syntax for now):
```
model CoolingCoilEffectivenessNTU3WayValve     // CoolingCoilEffectivenessNTU3WayValve is the configured model.
  extends VAVSingleDuct(    // VAVSingleDuct is the template class.
    redeclare replaceable record RecordCoiCoo = Coils.Data.WaterBased (
      redeclare 
        Buildings.Experimental.Templates.AHUs.Coils.HeatExchangers.Data.EffectivenessNTU
        datHex, redeclare 
        Buildings.Experimental.Templates.AHUs.Coils.Actuators.Data.ThreeWayValve
        datAct),
    redeclare Coils.WaterBased coiCoo(redeclare 
      Buildings.Experimental.Templates.AHUs.Coils.Actuators.ThreeWayValve
      act, redeclare 
      Buildings.Experimental.Templates.AHUs.Coils.HeatExchangers.EffectivenessNTU
      coi));
```

**Review by hubertus65 — COMMENTED** [review]
I have added a number of comments to the pdf file, inlined. I'll figure out how to upload it to a pull request and then link the file in a separate comment. 

[Linkage-Comments-HT.pdf](https://github.com/lbl-srg/linkage.js/files/6052767/Linkage-Comments-HT.pdf)

**Comment by AntoineGautier** [comment]
Here are the answers to @hubertus65 comments. The corresponding changes are included in the last commit.

> Table 3.2. Only Modelica tools can do this. Would not an update mechanism independent of Modelica-specific scripts be better (ask for new download or switch to older version etc.). Our industrial customers typically DO NOT update versions during the lifetime of a project, to avoid complications/added work.

Agreed.
If the version number does not match, the tool simply alerts the user of version incompatibility.

> §3.3. These following 4 bullets need a Modelica compiler behind. Is it understood that they are out of scope for  phase 1?

I further specified the scope of what needs to be supported in Phase 1, especially only literals, operations with literals and arrays constructors with literals need to be supported.

> §3.3. I am not sure Vendor-specific annotations are needed for that, but they are possible.  What is the purpose? To test for legal Modelica, it would be possible to compile (or check) only, but with missing parameters. A compiler is needed in any case. The model can not be simulated. It could be easier to have some kind of test-harness, that provides all necessary input to controls, but is not a building, and use that for some minimal tests. This could be better than a full buildings model.

No change in the specification. 
We need a mechanism to expose only a subset of the parameters in the control specification workflow. If no better alternative, a vendor annotation should be used.

> §3.3.1.1. I think it would be much better to allow only a subset, e.g. literals only check for type, and min and max. Why should this tool allow references to other modelica-variables or parameters?

It should not. In Phase 1, only literals, operations with literals and arrays constructors with literals need to be supported. This has been added to the specification.

> §3.3.1.2. This requires users to know and understand Modelica array constructors. Is that really desirable? Maybe doable with a tooltip that displays the syntax, but an "array input widget" is probably preferable, but not in the budget for phase 1. An array input widget requires fixed, know sizes, or simultaneously specified sizes.

No change in the specification. 
The widget is not budgeted. We will stick to the array constructor for the MVP in Phase I.

> §3.3.1.4. For fixed choices, this should be handled by and included in the json format. If no choices are in the library, the dropdown menu generation requires a list of allowable classes from the compiler. In phase 1, this must be pre-generated information. OCT has an internal API for this, but I am not sure it is already exposed in the public javascript-API.

Agreed. 
I clarified that in Phase 1, the discovery mechanism for ``choicesAllMatching`` will be implemented in the Modelica to JSON translator that will convert the ``choicesAllMatching`` annotation into a ``choices(choice)`` annotation when a specific flag is set to true. 

> §3.3.3. Can this really be done with access only to the generated json?

No change in the specification. 
We need a mechanism to constrain the available choices based on parameter values. If no better alternative, the vendor annotations specified in this paragraph should be used.

**Pull request merged**
